import type { AvatarFullConfig } from "react-nice-avatar";

export interface AvatarPreset {
  id: string;
  config: AvatarFullConfig;
}

export const avatarPresets: AvatarPreset[] = [
  {
    id: "copper-short",
    config: {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "small",
      hairColor: "#77311D",
      hairStyle: "womanShort",
      hatColor: "#F48150",
      hatStyle: "none",
      eyeStyle: "circle",
      eyeBrowStyle: "upWoman",
      glassesStyle: "none",
      noseStyle: "short",
      mouthStyle: "smile",
      shirtStyle: "short",
      shirtColor: "#F48150",
      bgColor: "#FFEBA4",
    },
  },
  {
    id: "amber-long",
    config: {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "big",
      hairColor: "#F48150",
      hairStyle: "womanLong",
      hatColor: "#77311D",
      hatStyle: "none",
      eyeStyle: "smile",
      eyeBrowStyle: "upWoman",
      glassesStyle: "round",
      noseStyle: "round",
      mouthStyle: "laugh",
      shirtStyle: "polo",
      shirtColor: "#F4D150",
      bgColor: "#FFEDEF",
    },
  },
  {
    id: "walnut-normal",
    config: {
      sex: "man",
      faceColor: "#F9C9B6",
      earSize: "small",
      hairColor: "#77311D",
      hairStyle: "normal",
      hatColor: "#506AF4",
      hatStyle: "none",
      eyeStyle: "oval",
      eyeBrowStyle: "up",
      glassesStyle: "square",
      noseStyle: "long",
      mouthStyle: "peace",
      shirtStyle: "hoody",
      shirtColor: "#77311D",
      bgColor: "#D2EFF3",
    },
  },
  {
    id: "hazel-mohawk",
    config: {
      sex: "man",
      faceColor: "#AC6651",
      earSize: "big",
      hairColor: "#000",
      hairStyle: "mohawk",
      hatColor: "#FC909F",
      hatStyle: "none",
      eyeStyle: "circle",
      eyeBrowStyle: "up",
      glassesStyle: "none",
      noseStyle: "short",
      mouthStyle: "smile",
      shirtStyle: "short",
      shirtColor: "#F48150",
      bgColor: "#FFEBA4",
    },
  },
  {
    id: "maple-beanie",
    config: {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "small",
      hairColor: "#77311D",
      hairStyle: "womanLong",
      hatColor: "#F48150",
      hatStyle: "beanie",
      eyeStyle: "oval",
      eyeBrowStyle: "upWoman",
      glassesStyle: "none",
      noseStyle: "long",
      mouthStyle: "peace",
      shirtStyle: "hoody",
      shirtColor: "#F4D150",
      bgColor: "#E0DDFF",
    },
  },
  {
    id: "acorn-turban",
    config: {
      sex: "man",
      faceColor: "#AC6651",
      earSize: "small",
      hairColor: "#000",
      hairStyle: "thick",
      hatColor: "#77311D",
      hatStyle: "turban",
      eyeStyle: "smile",
      eyeBrowStyle: "up",
      glassesStyle: "round",
      noseStyle: "round",
      mouthStyle: "laugh",
      shirtStyle: "polo",
      shirtColor: "#F48150",
      bgColor: "#FFEDEF",
    },
  },
  {
    id: "pine-thick",
    config: {
      sex: "man",
      faceColor: "#F9C9B6",
      earSize: "big",
      hairColor: "#77311D",
      hairStyle: "thick",
      hatColor: "#F4D150",
      hatStyle: "none",
      eyeStyle: "circle",
      eyeBrowStyle: "up",
      glassesStyle: "none",
      noseStyle: "round",
      mouthStyle: "smile",
      shirtStyle: "short",
      shirtColor: "#6BD9E9",
      bgColor: "#FFEBA4",
    },
  },
  {
    id: "cedar-pink",
    config: {
      sex: "woman",
      faceColor: "#AC6651",
      earSize: "big",
      hairColor: "#FC909F",
      hairStyle: "womanShort",
      hatColor: "#000",
      hatStyle: "none",
      eyeStyle: "oval",
      eyeBrowStyle: "upWoman",
      glassesStyle: "square",
      noseStyle: "short",
      mouthStyle: "peace",
      shirtStyle: "polo",
      shirtColor: "#FC909F",
      bgColor: "#D2EFF3",
    },
  },
  {
    id: "ginger-round",
    config: {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "small",
      hairColor: "#F48150",
      hairStyle: "normal",
      hatColor: "#77311D",
      hatStyle: "none",
      eyeStyle: "smile",
      eyeBrowStyle: "upWoman",
      glassesStyle: "none",
      noseStyle: "round",
      mouthStyle: "laugh",
      shirtStyle: "hoody",
      shirtColor: "#77311D",
      bgColor: "#FFEDEF",
    },
  },
  {
    id: "mocha-square",
    config: {
      sex: "man",
      faceColor: "#AC6651",
      earSize: "small",
      hairColor: "#77311D",
      hairStyle: "normal",
      hatColor: "#F48150",
      hatStyle: "none",
      eyeStyle: "oval",
      eyeBrowStyle: "up",
      glassesStyle: "square",
      noseStyle: "long",
      mouthStyle: "smile",
      shirtStyle: "hoody",
      shirtColor: "#F4D150",
      bgColor: "#E0DDFF",
    },
  },
  {
    id: "sunset-beanie",
    config: {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "big",
      hairColor: "#77311D",
      hairStyle: "womanLong",
      hatColor: "#F4D150",
      hatStyle: "beanie",
      eyeStyle: "circle",
      eyeBrowStyle: "upWoman",
      glassesStyle: "round",
      noseStyle: "short",
      mouthStyle: "smile",
      shirtStyle: "short",
      shirtColor: "#F48150",
      bgColor: "#FFEBA4",
    },
  },
  {
    id: "espresso-turban",
    config: {
      sex: "man",
      faceColor: "#F9C9B6",
      earSize: "big",
      hairColor: "#000",
      hairStyle: "thick",
      hatColor: "#F48150",
      hatStyle: "turban",
      eyeStyle: "smile",
      eyeBrowStyle: "up",
      glassesStyle: "none",
      noseStyle: "round",
      mouthStyle: "peace",
      shirtStyle: "polo",
      shirtColor: "#77311D",
      bgColor: "#FFEDEF",
    },
  },
  {
    id: "apricot-oval",
    config: {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "small",
      hairColor: "#D2EFF3",
      hairStyle: "womanShort",
      hatColor: "#77311D",
      hatStyle: "none",
      eyeStyle: "oval",
      eyeBrowStyle: "upWoman",
      glassesStyle: "none",
      noseStyle: "long",
      mouthStyle: "laugh",
      shirtStyle: "polo",
      shirtColor: "#F4D150",
      bgColor: "#FFEBA4",
    },
  },
  {
    id: "clove-blue",
    config: {
      sex: "man",
      faceColor: "#AC6651",
      earSize: "small",
      hairColor: "#506AF4",
      hairStyle: "mohawk",
      hatColor: "#000",
      hatStyle: "none",
      eyeStyle: "circle",
      eyeBrowStyle: "up",
      glassesStyle: "round",
      noseStyle: "short",
      mouthStyle: "smile",
      shirtStyle: "short",
      shirtColor: "#6BD9E9",
      bgColor: "#D2EFF3",
    },
  },
  {
    id: "butter-short",
    config: {
      sex: "woman",
      faceColor: "#AC6651",
      earSize: "big",
      hairColor: "#fff",
      hairStyle: "womanShort",
      hatColor: "#F48150",
      hatStyle: "none",
      eyeStyle: "smile",
      eyeBrowStyle: "upWoman",
      glassesStyle: "square",
      noseStyle: "round",
      mouthStyle: "peace",
      shirtStyle: "hoody",
      shirtColor: "#F48150",
      bgColor: "#FFEBA4",
    },
  },
  {
    id: "nutmeg-normal",
    config: {
      sex: "man",
      faceColor: "#F9C9B6",
      earSize: "small",
      hairColor: "#F48150",
      hairStyle: "normal",
      hatColor: "#77311D",
      hatStyle: "none",
      eyeStyle: "oval",
      eyeBrowStyle: "up",
      glassesStyle: "none",
      noseStyle: "long",
      mouthStyle: "laugh",
      shirtStyle: "polo",
      shirtColor: "#F4D150",
      bgColor: "#FFEDEF",
    },
  },
  {
    id: "cinnamon-hat",
    config: {
      sex: "woman",
      faceColor: "#F9C9B6",
      earSize: "small",
      hairColor: "#77311D",
      hairStyle: "womanLong",
      hatColor: "#77311D",
      hatStyle: "turban",
      eyeStyle: "circle",
      eyeBrowStyle: "upWoman",
      glassesStyle: "none",
      noseStyle: "short",
      mouthStyle: "smile",
      shirtStyle: "short",
      shirtColor: "#77311D",
      bgColor: "#E0DDFF",
    },
  },
  {
    id: "caramel-glasses",
    config: {
      sex: "man",
      faceColor: "#F9C9B6",
      earSize: "big",
      hairColor: "#77311D",
      hairStyle: "thick",
      hatColor: "#F48150",
      hatStyle: "none",
      eyeStyle: "smile",
      eyeBrowStyle: "up",
      glassesStyle: "round",
      noseStyle: "round",
      mouthStyle: "peace",
      shirtStyle: "hoody",
      shirtColor: "#F48150",
      bgColor: "#FFEBA4",
    },
  },
  {
    id: "cream-polo",
    config: {
      sex: "woman",
      faceColor: "#AC6651",
      earSize: "small",
      hairColor: "#77311D",
      hairStyle: "normal",
      hatColor: "#F4D150",
      hatStyle: "none",
      eyeStyle: "oval",
      eyeBrowStyle: "upWoman",
      glassesStyle: "round",
      noseStyle: "long",
      mouthStyle: "smile",
      shirtStyle: "polo",
      shirtColor: "#6BD9E9",
      bgColor: "#FFEDEF",
    },
  },
  {
    id: "brown-beam",
    config: {
      sex: "man",
      faceColor: "#AC6651",
      earSize: "big",
      hairColor: "#fff",
      hairStyle: "mohawk",
      hatColor: "#77311D",
      hatStyle: "beanie",
      eyeStyle: "circle",
      eyeBrowStyle: "up",
      glassesStyle: "square",
      noseStyle: "short",
      mouthStyle: "laugh",
      shirtStyle: "short",
      shirtColor: "#77311D",
      bgColor: "#D2EFF3",
    },
  },
];

export function getAvatarPreset(id?: string): AvatarPreset | undefined {
  return avatarPresets.find((preset) => preset.id === id);
}
